import type { Campaign } from '@/types/campaign'
import type { Category, Product } from '@/types/product'

/**
 * Mock categories data
 */
export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'Electronics',
    slug: 'electronics',
    description: 'Latest electronics and gadgets',
    image: 'https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=300&h=300&fit=crop',
  },
  {
    id: '2', 
    name: 'Fashion',
    slug: 'fashion',
    description: 'Trendy clothing and accessories',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=300&h=300&fit=crop',
  },
  {
    id: '3',
    name: 'Home & Garden',
    slug: 'home-garden',
    description: 'Everything for your home',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=300&h=300&fit=crop',
  },
  {
    id: '4',
    name: 'Sports & Fitness',
    slug: 'sports-fitness',
    description: 'Sports equipment and fitness gear',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=300&h=300&fit=crop',
  },
  {
    id: '5',
    name: 'Beauty & Health',
    slug: 'beauty-health',
    description: 'Beauty products and health essentials',
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=300&h=300&fit=crop',
  },
  {
    id: '6',
    name: 'Books & Media',
    slug: 'books-media',
    description: 'Books, movies, and digital media',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=300&h=300&fit=crop',
  },
  {
    id: '7',
    name: 'Automotive',
    slug: 'automotive',
    description: 'Car accessories and parts',
    image: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=300&h=300&fit=crop',
  },
  {
    id: '8',
    name: 'Food & Beverage',
    slug: 'food-beverage',
    description: 'Gourmet food and beverages',
    image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=300&h=300&fit=crop',
  },
]

/**
 * Mock campaigns data
 */
export const mockCampaigns: Campaign[] = [
  {
    id: '1',
    title: 'Black Friday Mega Sale',
    description: 'Up to 70% off on selected electronics and fashion items',
    shortDescription: 'Up to 70% off electronics',
    type: 'flash_sale',
    status: 'active',
    discountType: 'percentage',
    discountValue: 70,
    bannerImage: 'https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?w=800&h=400&fit=crop',
    thumbnailImage: 'https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?w=300&h=200&fit=crop',
    categoryIds: ['1', '2'],
    usedCount: 234,
    startDate: '2024-01-15T00:00:00Z',
    endDate: '2024-01-30T23:59:59Z',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    priority: 1,
    showOnHomepage: true,
    isFeatured: true,
    backgroundColor: '#FF6B35',
    textColor: '#FFFFFF',
    slug: 'black-friday-mega-sale',
  },
  {
    id: '2',
    title: 'Daily Deal: Smart Watch',
    description: 'Limited time offer on premium smartwatches',
    shortDescription: '50% off smartwatches',
    type: 'daily_deal',
    status: 'active',
    discountType: 'percentage',
    discountValue: 50,
    bannerImage: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&h=400&fit=crop',
    thumbnailImage: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=300&h=200&fit=crop',
    productIds: ['2'],
    usageLimit: 100,
    usedCount: 45,
    startDate: '2024-01-20T00:00:00Z',
    endDate: '2024-01-21T23:59:59Z',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    priority: 2,
    showOnHomepage: true,
    isFeatured: true,
    backgroundColor: '#4ECDC4',
    textColor: '#FFFFFF',
    slug: 'daily-deal-smart-watch',
  },
  {
    id: '3',
    title: 'Free Shipping Weekend',
    description: 'Free shipping on all orders over $50',
    shortDescription: 'Free shipping over $50',
    type: 'free_shipping',
    status: 'active',
    discountType: 'free_shipping',
    discountValue: 0,
    bannerImage: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=800&h=400&fit=crop',
    thumbnailImage: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=300&h=200&fit=crop',
    minOrderAmount: 50,
    usedCount: 89,
    startDate: '2024-01-22T00:00:00Z',
    endDate: '2024-01-24T23:59:59Z',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    priority: 3,
    showOnHomepage: true,
    isFeatured: false,
    backgroundColor: '#45B7D1',
    textColor: '#FFFFFF',
    slug: 'free-shipping-weekend',
  },
]

/**
 * Mock product data for development and testing
 */
export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Premium Wireless Headphones',
    slug: 'premium-wireless-headphones',
    description: 'High-quality wireless headphones with noise cancellation and premium sound quality.',
    shortDescription: 'Premium wireless headphones with noise cancellation',
    price: 199.99,
    originalPrice: 249.99,
    discount: 50,
    discountPercentage: 20,
    sku: 'WH-001',
    stock: 15,
    lowStockThreshold: 5,
    isInStock: true,
    images: [
      {
        id: '1',
        url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&h=500&fit=crop',
        alt: 'Premium Wireless Headphones',
        isPrimary: true,
        order: 1,
      },
      {
        id: '2',
        url: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=500&h=500&fit=crop',
        alt: 'Premium Wireless Headphones Side View',
        isPrimary: false,
        order: 2,
      },
    ],
    categoryId: '1',
    category: mockCategories[0],
    tags: ['wireless', 'audio', 'premium'],
    reviews: [],
    averageRating: 4.8,
    totalReviews: 124,
    isActive: true,
    isFeatured: true,
    isOnSale: true,
    isNew: false,
    isBestSeller: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Smartwatch Pro',
    slug: 'smartwatch-pro',
    description: 'Advanced smartwatch with health monitoring and fitness tracking capabilities.',
    price: 299.99,
    sku: 'SW-002',
    stock: 8,
    lowStockThreshold: 10,
    isInStock: true,
    images: [
      {
        id: '3',
        url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=500&fit=crop',
        alt: 'Smartwatch Pro',
        isPrimary: true,
        order: 1,
      },
    ],
    categoryId: '1',
    category: mockCategories[0],
    tags: ['smartwatch', 'fitness', 'health'],
    reviews: [],
    averageRating: 4.6,
    totalReviews: 89,
    isActive: true,
    isFeatured: false,
    isOnSale: false,
    isNew: true,
    isBestSeller: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    name: 'Eco-Friendly Water Bottle',
    slug: 'eco-friendly-water-bottle',
    description: 'Sustainable stainless steel water bottle with temperature retention.',
    price: 29.99,
    originalPrice: 39.99,
    discountPercentage: 25,
    sku: 'WB-003',
    stock: 50,
    isInStock: true,
    images: [
      {
        id: '4',
        url: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=500&h=500&fit=crop',
        alt: 'Eco-Friendly Water Bottle',
        isPrimary: true,
        order: 1,
      },
    ],
    categoryId: '4',
    category: mockCategories[3],
    tags: ['eco-friendly', 'bottle', 'sustainable'],
    reviews: [],
    averageRating: 4.4,
    totalReviews: 67,
    isActive: true,
    isFeatured: false,
    isOnSale: true,
    isNew: false,
    isBestSeller: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '4',
    name: 'Ergonomic Office Chair',
    slug: 'ergonomic-office-chair',
    description: 'Comfortable ergonomic office chair with lumbar support and adjustable height.',
    price: 349.99,
    sku: 'OC-004',
    stock: 0,
    isInStock: false,
    images: [
      {
        id: '5',
        url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500&h=500&fit=crop',
        alt: 'Ergonomic Office Chair',
        isPrimary: true,
        order: 1,
      },
    ],
    categoryId: '3',
    category: mockCategories[2],
    tags: ['office', 'chair', 'ergonomic'],
    reviews: [],
    averageRating: 4.7,
    totalReviews: 156,
    isActive: true,
    isFeatured: false,
    isOnSale: false,
    isNew: false,
    isBestSeller: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '5',
    name: 'Organic Cotton T-Shirt',
    slug: 'organic-cotton-t-shirt',
    description: 'Soft and comfortable organic cotton t-shirt in various colors.',
    price: 24.99,
    sku: 'TS-005',
    stock: 3,
    lowStockThreshold: 5,
    isInStock: true,
    images: [
      {
        id: '6',
        url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop',
        alt: 'Organic Cotton T-Shirt',
        isPrimary: true,
        order: 1,
      },
    ],
    categoryId: '2',
    category: mockCategories[1],
    tags: ['organic', 'cotton', 'clothing'],
    reviews: [],
    averageRating: 4.3,
    totalReviews: 92,
    isActive: true,
    isFeatured: false,
    isOnSale: false,
    isNew: true,
    isBestSeller: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '6',
    name: 'Professional Camera Lens',
    slug: 'professional-camera-lens',
    description: 'High-quality professional camera lens for photography enthusiasts.',
    price: 899.99,
    sku: 'CL-006',
    stock: 12,
    isInStock: true,
    images: [
      {
        id: '7',
        url: 'https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=500&h=500&fit=crop',
        alt: 'Professional Camera Lens',
        isPrimary: true,
        order: 1,
      },
    ],
    categoryId: '1',
    category: mockCategories[0],
    tags: ['camera', 'lens', 'photography'],
    reviews: [],
    averageRating: 4.9,
    totalReviews: 203,
    isActive: true,
    isFeatured: true,
    isOnSale: false,
    isNew: false,
    isBestSeller: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '7',
    name: 'Wireless Gaming Mouse',
    slug: 'wireless-gaming-mouse',
    description: 'High-precision wireless gaming mouse with RGB lighting.',
    price: 79.99,
    originalPrice: 99.99,
    discountPercentage: 20,
    sku: 'GM-007',
    stock: 25,
    isInStock: true,
    images: [
      {
        id: '8',
        url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500&h=500&fit=crop',
        alt: 'Wireless Gaming Mouse',
        isPrimary: true,
        order: 1,
      },
    ],
    categoryId: '1',
    category: mockCategories[0],
    tags: ['gaming', 'mouse', 'wireless'],
    reviews: [],
    averageRating: 4.5,
    totalReviews: 178,
    isActive: true,
    isFeatured: true,
    isOnSale: true,
    isNew: true,
    isBestSeller: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '8',
    name: 'Luxury Skincare Set',
    slug: 'luxury-skincare-set',
    description: 'Complete luxury skincare routine with natural ingredients.',
    price: 129.99,
    sku: 'LS-008',
    stock: 18,
    isInStock: true,
    images: [
      {
        id: '9',
        url: 'https://images.unsplash.com/photo-1570194065650-d99c79653827?w=500&h=500&fit=crop',
        alt: 'Luxury Skincare Set',
        isPrimary: true,
        order: 1,
      },
    ],
    categoryId: '5',
    category: mockCategories[4],
    tags: ['skincare', 'luxury', 'natural'],
    reviews: [],
    averageRating: 4.7,
    totalReviews: 95,
    isActive: true,
    isFeatured: true,
    isOnSale: false,
    isNew: true,
    isBestSeller: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '8',
    name: 'Luxury Skincare Set',
    slug: 'luxury-skincare-set',
    description: 'Complete luxury skincare routine with natural ingredients.',
    price: 129.99,
    sku: 'LS-008',
    stock: 18,
    isInStock: true,
    images: [
      {
        id: '9',
        url: 'https://images.unsplash.com/photo-1570194065650-d99c79653827?w=500&h=500&fit=crop',
        alt: 'Luxury Skincare Set',
        isPrimary: true,
        order: 1,
      },
    ],
    categoryId: '5',
    category: mockCategories[4],
    tags: ['skincare', 'luxury', 'natural'],
    reviews: [],
    averageRating: 4.7,
    totalReviews: 95,
    isActive: true,
    isFeatured: true,
    isOnSale: false,
    isNew: true,
    isBestSeller: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '8',
    name: 'Luxury Skincare Set',
    slug: 'luxury-skincare-set',
    description: 'Complete luxury skincare routine with natural ingredients.',
    price: 129.99,
    sku: 'LS-008',
    stock: 18,
    isInStock: true,
    images: [
      {
        id: '9',
        url: 'https://images.unsplash.com/photo-1570194065650-d99c79653827?w=500&h=500&fit=crop',
        alt: 'Luxury Skincare Set',
        isPrimary: true,
        order: 1,
      },
    ],
    categoryId: '5',
    category: mockCategories[4],
    tags: ['skincare', 'luxury', 'natural'],
    reviews: [],
    averageRating: 4.7,
    totalReviews: 95,
    isActive: true,
    isFeatured: true,
    isOnSale: false,
    isNew: true,
    isBestSeller: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '8',
    name: 'Luxury Skincare Set',
    slug: 'luxury-skincare-set',
    description: 'Complete luxury skincare routine with natural ingredients.',
    price: 129.99,
    sku: 'LS-008',
    stock: 18,
    isInStock: true,
    images: [
      {
        id: '9',
        url: 'https://images.unsplash.com/photo-1570194065650-d99c79653827?w=500&h=500&fit=crop',
        alt: 'Luxury Skincare Set',
        isPrimary: true,
        order: 1,
      },
    ],
    categoryId: '5',
    category: mockCategories[4],
    tags: ['skincare', 'luxury', 'natural'],
    reviews: [],
    averageRating: 4.7,
    totalReviews: 95,
    isActive: true,
    isFeatured: true,
    isOnSale: false,
    isNew: true,
    isBestSeller: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '8',
    name: 'Luxury Skincare Set',
    slug: 'luxury-skincare-set',
    description: 'Complete luxury skincare routine with natural ingredients.',
    price: 129.99,
    sku: 'LS-008',
    stock: 18,
    isInStock: true,
    images: [
      {
        id: '9',
        url: 'https://images.unsplash.com/photo-1570194065650-d99c79653827?w=500&h=500&fit=crop',
        alt: 'Luxury Skincare Set',
        isPrimary: true,
        order: 1,
      },
    ],
    categoryId: '5',
    category: mockCategories[4],
    tags: ['skincare', 'luxury', 'natural'],
    reviews: [],
    averageRating: 4.7,
    totalReviews: 95,
    isActive: true,
    isFeatured: true,
    isOnSale: false,
    isNew: true,
    isBestSeller: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '8',
    name: 'Luxury Skincare Set',
    slug: 'luxury-skincare-set',
    description: 'Complete luxury skincare routine with natural ingredients.',
    price: 129.99,
    sku: 'LS-008',
    stock: 18,
    isInStock: true,
    images: [
      {
        id: '9',
        url: 'https://images.unsplash.com/photo-1570194065650-d99c79653827?w=500&h=500&fit=crop',
        alt: 'Luxury Skincare Set',
        isPrimary: true,
        order: 1,
      },
    ],
    categoryId: '5',
    category: mockCategories[4],
    tags: ['skincare', 'luxury', 'natural'],
    reviews: [],
    averageRating: 4.7,
    totalReviews: 95,
    isActive: true,
    isFeatured: true,
    isOnSale: false,
    isNew: true,
    isBestSeller: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
]

/**
 * Homepage specific mock data helpers
 */
export const getHomepageData = () => {
  return {
    featuredProducts: mockProducts.filter(p => p.isFeatured).slice(0, 20),
    newArrivals: mockProducts.filter(p => p.isNew).slice(0, 20),
    popularProducts: mockProducts.filter(p => p.isBestSeller).slice(0, 20),
    featuredCategories: mockCategories.slice(0, 20),
    campaigns: mockCampaigns.filter(c => c.showOnHomepage),
    dailyDeals: mockCampaigns.filter(c => c.type === 'daily_deal'),
    flashSales: mockCampaigns.filter(c => c.type === 'flash_sale'),
  }
} 